# Javascript Node CircleCI 2.0 configuration file
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
version: 2
jobs:
  build:
    docker:
      # https://hub.docker.com/r/circleci/node/
      - image: circleci/node:10.14.1
      # https://circleci.com/docs/2.0/circleci-images/#mongodb
      - image: circleci/mongo:4.0
      # https://circleci.com/docs/2.0/circleci-images/#redis (on tourne avec une 3.2.6 en prod, mais y'a que 4.0 chez circleci
      - image: circleci/redis:4.0

    working_directory: ~/lassi
    environment:
      - CIRCLE_CI: true

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      # Bof, mais sans cela NPM râle avec "node_modules/sesajstools: Appears to be a git repo or submodule."
      - run: rm -rf ~/lassi/node_modules/sesajstools/.git

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: npm test
